### ISSUE TITLE
reject:file is too big

### ISSUE THREAD

**Issue by maohanghang** [kochetkov-ma/allure-server#54]
when the allure log file size is 395M，it occurs a problem，as below：
![image](https://user-images.githubusercontent.com/23241083/210296520-76989911-012d-45b8-aad1-2d6a30e0cb6e.png)

how to solve this problem？thanks

**Comment by kochetkov-ma** [comment]
Please see
- File to large to upload #52 
- Request entity too large Error #42
- Configurable upload size #16

There are two parameters in the Spring settings:

```
spring:
  servlet:
    multipart.max-file-size: 100MB
    multipart.max-request-size: 100MB
```

It can be specified via environment variables when you start the container: 
`spring_servlet_multipart_maxRequestSize=1000MB`
`spring_servlet_multipart_maxFileSize=1000MB`

Try this ...

In Kubernetes you still need to enable the setting for nginx ingress :

```
  annotations:
    kubernetes.io/ingress.class: nginx
    ## deprecated
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    ## deprecated
    nginx.ingress.kubernetes.io/client-max-body-size: "100m"
    ## new https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/
    nginx.org/client-max-body-size: "100m"
```
