### ISSUE TITLE
Поправить описание системных переменных

### ISSUE THREAD

**Issue by lifanov-rza** [kochetkov-ma/allure-server#58]
По доке непонятно как надо преобразовать системную переменную при запуске контейнера, чтобы поправить конфиги.

Хочу изменить значения:

- allure.reports.history-level
- allure.clean.ageDays

Судя из [документации](https://docs.spring.io/spring-boot/docs/1.5.5.RELEASE/reference/html/boot-features-external-config.html) имена должны свестись к такому формату:

- ALLURE_REPORTS_HISTORY_LEVEL
- ALLURE_CLEAN_AGE_DAYS

Пробовал следующие вариации, не работает:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/48446944/213707427-f93f1273-ee49-4ceb-9518-de8bf73649f8.png">

В этом [ишью](https://github.com/kochetkov-ma/allure-server/issues/54) видел, что тире преобразовываются в camelcase

Выше по доке (над таблицей) сказано, что надо использовать имя через точку, а не через нижнее подчёркивание
![image](https://user-images.githubusercontent.com/48446944/213707985-dd992bf6-3b6d-4b38-ba02-419f742bd2c4.png)

Прошу поправить доку и дать ответ какие имена переменных контейнера надо использовать, чтобы поправить конфиги

**Comment by lifanov-rza** [comment]
косяк в коде, значения захардкожены. Можно поискать введя "20"

**Comment by lifanov-rza** [comment]
для теста, изменил значение значение в `application.yaml`:

`history-level: 2`

по итогу, значение с конфига не подтягивается в код
![image](https://user-images.githubusercontent.com/48446944/213780768-4d7a6393-2bf8-4959-8c1c-f070c1b6eac8.png)

Далее поправил в коде значение в конструкторе Reports - всё отработало как надо для таблицы отчётов. 

```
public Reports() {
            this("allure/reports/", "reports/", 2);
        }
```

Историю отчётов проверять не стал, думаю там всё так же и надо поправить

**Comment by ygelfand** [comment]
this is (at least partially) addressed https://github.com/kochetkov-ma/allure-server/pull/55

**Comment by kochetkov-ma** [comment]
https://github.com/kochetkov-ma/allure-server/releases/tag/v2.11.4 Fixed

Add parameters logging with prefix `[ALLURE SERVER CONFIGURATION]`

Example Environment Variables for overriding (I checked it - it works):
- `ALLURE_CLEAN_DRYRUN=true`
- `ALLURE_REPORTS_HISTORYLEVEL=1`

**Comment by QAAAAAAAA** [comment]
seems can not find the `ALLURE_REPORTS_HISTORYLEVEL ` in the log. @kochetkov-ma  can help check?

```
allure-server_1  | 2023-05-24 03:14:19.317  INFO 1 --- [           main] r.i.q.a.s.CleanUpServiceConfiguration    : [ALLURE SERVER CONFIGURATION] CleanUp policy settings:
allure-server_1  | {
allure-server_1  |   "dryRun" : true,
allure-server_1  |   "time" : "00:00:00",
allure-server_1  |   "ageDays" : 180,
allure-server_1  |   "paths" : [ {
allure-server_1  |     "path" : "manual_uploaded",
allure-server_1  |     "ageDays" : 30,
allure-server_1  |     "edgeDate" : "2023-04-24T03:14:19.316708"
allure-server_1  |   } ],
allure-server_1  |   "minAge" : 30,
allure-server_1  |   "closestEdgeDate" : "2023-04-24T03:14:19.31691",
allure-server_1  |   "edgeDate" : "2022-11-25T03:14:19.316962",
allure-server_1  |   "notDryRun" : false
allure-server_1  | }
```

Its my compose yaml 

```
version: "3.7"
services:
  allure-server:
    # For local debug #
    # build: .
    image: kochetkovma/allure-server:2.11.4
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/allure
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE: postgresql
      SPRING_JPA_HIBERNATE_DDL-AUTO: update # Careful! 'create' destroy data! https://stackoverflow.com/questions/21113154/spring-boot-ddl-auto-generator
      spring_servlet_multipart_maxRequestSize: 1000MB
      spring_servlet_multipart_maxFileSize: 1000MB
      ALLURE_CLEAN_DRYRUN: true
      ALLURE_CLEAN_AGEDAYS: 180
      ALLURE_REPORTS_HISTORYLEVEL: 2
    ports:
      - 7070:8080
    volumes:
      - ./ext:/ext:rw
      - ./allure-server-store:/allure:rw
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: allure
    volumes:
      - ./db_data:/var/lib/postgresql/data:Z
    ports:
      - 15432:5432

```
