### ISSUE TITLE
Save data if container is down

### ISSUE THREAD

**Issue by aakhmetshin** [kochetkov-ma/allure-server#6]
I'm new to ur service
what if container is killed? all the reports would be lost?
should I organise some back-up using 
GET ​/api​/report ?

**Comment by kochetkov-ma** [comment]
You should use volume for database and reports dir.
For example in docker-compose :
```
version: '3.7'
services:
  allure-server:
    container_name: allure-server
    image: kochetkovma/allure-server:latest
    ports:
      - 8080:8080
    volumes:
      - /your-root-directory/allure-server:/allure
```
It will map `/your-root-directory/allure-server` directory on your Linux file system to '/allure' dir from the container. By default everything is stored to '/allure' dir in the container
