### ISSUE TITLE
Reject: File is Too Big.

### ISSUE THREAD

**Issue by 0x00nullnonenil** [kochetkov-ma/allure-server#61]
`org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (176460570) exceeds the configured maximum (104857600)`

when I uploaded the file

**Comment by zimaev** [comment]
Аналогичная проблема при загрузке отчете через UI.

**Comment by kochetkov-ma** [comment]
```
spring:
  servlet:
    multipart.max-file-size: 100MB
    multipart.max-request-size: 100MB
```

override settings via env variable: `spring_servlet_multipart_maxfilesize` and `maxrequestsize`
