### ISSUE TITLE
How to use postgresql?

### ISSUE THREAD

**Issue by evsasha** [kochetkov-ma/allure-server#68]
Hello, I am trying to use a Helm chart with a PostgreSQL backend.

However, in my PostgreSQL database, I can only see one table: 'report_entity'.

Does the Allure server not store Allure results in the database?

In my scenario, if I lose the PVC, I lose all the data.

Although the Allure server finds the reports in the database, it cannot display them.

**Comment by evsasha** [comment]
My helm values:

```yaml
ingress:
  enabled: false

pvc:
  enabled: true
  spec:
    storageClassName: vsphere
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

databaseCrt:
  enabled: false

env:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.cluster.local:5432/allure?&targetServerType=master&useSSL=true"
  SPRING_JPA_DATABASE: postgresql
  SPRING_JPA_HIBERNATE_DDL-AUTO: update
```
